FROM nvidia/cuda:12.4.1-cudnn-runtime-rockylinux8 

RUN cat /etc/os-release
RUN dnf search python | grep ^python | grep -i interpreter
RUN dnf install python3.8
RUN ls -l /usr/bin | grep python

COPY . /MedImageInsights
WORKDIR /MedImageInsights

RUN python -V
RUN pip install uv
RUN uv --version
RUN uv python list

RUN uv sync
CMD uv run fastapi_app.py

EXPOSE 8000
