FROM nvidia/cuda:12.4.1-cudnn-runtime-rockylinux8 

COPY . /MedImageInsights
WORKDIR /MedImageInsights

RUN python -V
RUN pip install uv
RUN uv --version
RUN uv python list

RUN uv sync
CMD uv run fastapi_app.py

EXPOSE 8000
